### ISSUE TITLE
[Space] - Fairdrop research

### ISSUE THREAD

**Issue by devformatters** [thematters/developer-resource#104]
tasks
-Twitter / Discord

**Comment by robertu7** [comment]
### User Flow

1. [Client] Sign In with Ethereum;
2. [Client] Send a Tweet with pre-defined content (`nonce`);
3. [Server] Verify and return a signed `nonce` message with the server private key;  
4. [Client] Sign and send a transaction with the message;
5. [Contract] Verify the message if it's signed by server private key and send $SPACE token;
