### ISSUE TITLE
[Dev] Onboarding plan

### ISSUE THREAD

**Issue by devformatters** [thematters/developer-resource#109]

**Comment by devformatters** [comment]
@guoliu

There's an old [issue](https://github.com/thematters/developer-resource/issues/25) might related to this. If you've added it, please close that issue. Thank you so much. 🤴🏿

**Comment by guoliu** [comment]
@devformatters It has not been resolved, let's move it to the current sprint 🌿

**Comment by robertu7** [comment]
Closed since we have made a lot of changes to [Engineer Handbook](https://www.notion.so/matterslab/Engineering-Handbook-6288ce2a4f0846d181d45526244323f6), including [Onboarding](https://www.notion.so/matterslab/Onboarding-31118225b8484fb5a04b8378d0cd281f).
