### ISSUE TITLE
Intro to main codebases and architectures of matters.news

### ISSUE THREAD

**Issue by robertu7** [thematters/developer-resource#114]
* intro to current architectures, basiclly same as https://github.com/thematters/developer-resource/;
* deep explanation of some topics like performance:
    * GraphQL & Apollo related cache optimization;
      * https://github.com/thematters/apollo-response-cache 
    * How to optimize cache hit rate via client [request breakdown](https://paper.dropbox.com/doc/JAMstack-break-queries-into-public-and-private--Bfj5oyXvjpFlzkLiW2wBX31NAQ-gzJ3KkGTt40RD5wj5F35A);

**Comment by Jasmine-liang** [comment]
Also can explain the bottleneck of one repo. E.g. [There's situation that data might be lost](https://github.com/thematters/serverless-ipfs-node-management)

**Comment by robertu7** [comment]
https://www.notion.so/matterslab/What-happens-when-you-type-matters-news-3a72c23e280243a88b66d792902e7bed

**Comment by robertu7** [comment]
https://www.notion.so/matterslab/What-happens-when-you-type-matters-news-3a72c23e280243a88b66d792902e7bed

**Comment by devformatters** [comment]
Close it. Feel free to reopen or create new issues if needs.
