### ISSUE TITLE
AWS costs review

### ISSUE THREAD

**Issue by robertu7** [thematters/developer-resource#116]
**Checklist**
- [x] review [AWS costs](https://us-east-1.console.aws.amazon.com/billing/home?region=ap-southeast-1#/bills?year=2022&month=6) and update to [doc](https://paper.dropbox.com/doc/Optimizing-AWS-Costs-zqUvrcxOOFaN1ba9mvQ04);
- [x] solutions to optimize costs;
  * terminate unused services;
  * downgrade instances types;
  * ...
  * saving plan or thrid-party partner;

**Refs**
* [Key ways to start optimizing your AWS cloud costs
](https://aws.amazon.com/cn/blogs/aws-cloud-financial-management/key-ways-to-start-optimizing-your-aws-cloud-costs/)
* [AWS Cost Optimizations: Tools, Checklist, and Best Practices](https://cloud.netapp.com/blog/3-ways-to-save-big-and-10-price-variations-to-know-aws-cvo-blg)

**Comment by devformatters** [comment]
Implementation tasks are created, so close it this one.
