### ISSUE TITLE
SEO Audit of matters.news (with webpagetest.org)

### ISSUE THREAD

**Issue by devformatters** [thematters/developer-resource#118]
https://www.webpagetest.org/result/220428_AiDcG0_GT3/  Test from Taiwan, with iPhoneX simulated Cable (Connectivity: 5000/1000 Kbps, 28ms Latency)

1. many 403s in network requests flow, like https://matters.news/_next//static/media/apple-touch-icon.a3ca0370.png
2. connections to server.matters.news (should be all server rendering?)
3. Total Number of Requests 382 (can cut down?)

(Test Error: 403 Navigation error)
(Error: 403)

**Comment by robertu7** [comment]
Closed due to no updates for too long, feel free to reopen.
