### ISSUE TITLE
SEO Audit of matters.news (with pagespeed.web.dev)

### ISSUE THREAD

**Issue by devformatters** [thematters/developer-resource#119]
1. Core Web Vitals Assessment: Failed
2. Largest Contentful Paint (LCP) 4.9s is too long
3. Reduce initial server response time 1.57s
4. Serve images in next-gen formats (mostly announcementCover)
5. Serve static assets with an efficient cache policy 100 resources found (assets.matters.news S3 bucket policy)
6. Avoid enormous network payloads Total size was 3,237 KiB

Content wider than screen
First detected: 12/2/19
Status: Error

https://pagespeed.web.dev/report?url=https%3A%2F%2Fmatters.news%2F%40astrid928art%2F257975
/avatar/b1bea2ab-112a-4cb9-8fa1-270…cc.gif(assets.matters.news)
4,122.5 KiB
Properly size images
19.93 s

https://seositecheckup.com/seo-audit/matters.news/@astrid928art/257975

**Comment by robertu7** [comment]
Closed since we have made some progress in https://github.com/thematters/developer-resource/issues/191
