### ISSUE TITLE
SEO Audit of matters.news (with seositecheckup.com)

### ISSUE THREAD

**Issue by devformatters** [thematters/developer-resource#120]
https://seositecheckup.com/seo-audit/matters.news

1. SEO Score (66/100)
2. Some of your website's JavaScript files are not minified!
3. Your webpage contains URLs that are not SEO friendly!
4. Your website is not using a custom 404 error page
5. https://matters.news and https://www.matters.news should resolve to the same URL, but currently do not.
6. This webpage is not serving images in a modern format (announcementCover)
7. The size of your webpage's HTML is 46.69 Kb, and is greater than the average size of 33 Kb
8. Your website is not connected with social media using the API's provided by Facebook, Google +, Twitter
9. Your webpage is using "img" tags with empty or missing "alt" attribute.
9. ... (more)

**Comment by robertu7** [comment]
Closed due to no updates for too long, feel free to reopen.
