### ISSUE TITLE
[Design] Token donation and wallet redesign

### ISSUE THREAD

**Issue by devformatters** [thematters/developer-resource#122]
### Tasks
- [x] Design how Token donation work
- [ ] Design how to read on-chain data
- [ ] Require a documentation

### References
- [Product doc](https://paper.dropbox.com/doc/Matters-USDT--Blk5iTpOUQKZQ3O~W5RSUEYaAg-hk1wXd1o4TXE86yGEsZTZ)

**Comment by guoliu** [comment]
Documentation: https://www.notion.so/matterslab/USDT-Donation-c1035628b7614b54a0e926e724ded7d9

**Comment by robertu7** [comment]
Duplicate with https://github.com/thematters/contracts/issues/107
