### ISSUE TITLE
[Design] Present translated article content

### ISSUE THREAD

**Issue by devformatters** [thematters/developer-resource#123]
### Tasks
- [ ] Design how to cost-effectively store and present translated content
- [ ] Design API for article card using translated content
- [ ] Required a documentation

### References
- [Product doc](https://paper.dropbox.com/doc/Matters-CIYsKQj8cmr4STCXWQIxA)

**Comment by guoliu** [comment]
Working documentation: https://www.notion.so/matterslab/matters-news-bee06757e0d64860accf6ca46ab560ac

**Comment by devformatters** [comment]
Close it cuz we're developing it.
