### ISSUE TITLE
Understanding the network traffic of matters.news

### ISSUE THREAD

**Issue by robertu7** [thematters/developer-resource#142]
* From DNS to the origin servers, what kinds of traffic are being routed within our network?
* How to monitor, detect and control them?
* How to optimize them for security and performance?
* What actions should we take when an accident (e.g. DDoS, exposed private network) happens?

**Comment by Jasmine-liang** [comment]
Great, would it be better to output a guide that even a new developer can follow when ddos comes?

**Comment by guoliu** [comment]
We can start with the following:

- [ ] collect related data
- [ ] clean data for sensitive info, and save as public record

**Comment by robertu7** [comment]
https://www.notion.so/matterslab/What-happens-when-you-type-matters-news-3a72c23e280243a88b66d792902e7bed

**Comment by devformatters** [comment]
Close it cuz there's an article explained it, and no more other todo at the moment. Feel free to reopen it or create an new issue related to it.
