### ISSUE TITLE
[Doc] Recap DDoS attacks

### ISSUE THREAD

**Issue by robertu7** [thematters/developer-resource#144]
### Tasks
- [ ] Analyze logs: AWS Elastic Beanstalk, AWS WAF, Cloudflare;
- [ ] Doc and article to review this accident;

**Comment by robertu7** [comment]
Since CloudWatch logs of Elastic Beanstalk (`matters-client-prod` and `matters-server-prod`) are 30 days rolling, @guoliu i have exported them (past 30 days) to [S3](https://s3.console.aws.amazon.com/s3/buckets/cloudwatch-logs-eb?region=ap-southeast-1&prefix=wKm34XxgOl%2F&showversions=false).

For CloudFront's, I saw [they are missing](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/aws-waf-logs-client) and didn't know the reason. I have exported the insight data and sent you on Slack.

**Comment by guoliu** [comment]
> Since CloudWatch logs of Elastic Beanstalk (`matters-client-prod` and `matters-server-prod`) are 30 days rolling, @guoliu i have exported them (past 30 days) to [S3](https://s3.console.aws.amazon.com/s3/buckets/cloudwatch-logs-eb?region=ap-southeast-1&prefix=wKm34XxgOl%2F&showversions=false).
> 
> For CloudFront's, I saw [they are missing](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/aws-waf-logs-client) and didn't know the reason. I have exported the insight data and sent you on Slack.

Sounds good, if we can't get CloudFront's request history let's use Cloudflare's.

**Comment by guoliu** [comment]
Article draft: https://paper.dropbox.com/doc/DDoS-eup4xfLZ70JTOYXnsOsFi
