### ISSUE TITLE
Testing: Mos Eisley

### ISSUE THREAD

**Issue by robertu7** [thematters/developer-resource#154]
### Introduction
In previous epic [Testing: Peli Motto #136](https://github.com/thematters/developer-resource/issues/136), we setup testing framework (playwright) to [matters-web](https://github.com/thematters/matters-web) and integrated to CI/CD workflow.

In this epic, we are going to cover more scenarios on testing, including prioritized pages like homepage and article details, or features like article publishing.

### Roadmap
* ✅Setup Testing Framework
* ➡️ Add more test cases, find best practices & make document
* Integrate into daily workflow

### Tasks
- https://github.com/thematters/matters-web/issues/2788
- https://github.com/thematters/matters-web/issues/2957
- https://github.com/thematters/matters-web/issues/2958
- https://github.com/thematters/matters-web/issues/2959
- https://github.com/thematters/matters-web/issues/2977

**Comment by Jasmine-liang** [comment]
Resources that worth reading:
- [Effective Software Testing: A developer's guide](https://book4you.org/book/21038925/789484)
