### ISSUE TITLE
IPFS pinning solution

### ISSUE THREAD

**Issue by tx0c** [thematters/developer-resource#157]
### Tasks
- [x] Solution documentation
- [x] Implementation pinning service
- [x] Resolve full-disk IPFS node cannot access problem

### References

- improve accessibility & reliability
- with services like https://docs.filebase.com/api-documentation/ipfs-pinning-service-api
- [slack](https://mattersnews.slack.com/archives/GA0R09FHN/p1665712842345659?thread_ts=1665572996.220219&cid=GA0R09FHN)

**Comment by devformatters** [comment]
Utilize ISCN upload feature?

**Comment by tx0c** [comment]
https://www.notion.so/matterslab/Matters-IPFS-HA-High-Availability-Improvement-1285644165cc487a9f9aae832f3673a6
