### ISSUE TITLE
Currency converter solution

### ISSUE THREAD

**Issue by devformatters** [thematters/developer-resource#164]
### Tasks
- [ ] design ~both FE-only~ and backend solutions for currency conversion. Please consider:
  - It's unnecessary to be real time
  - most 3rd party APIs have request limits, so might need to utilize cache 
- [ ] output documentation about the solution, and API schema & DB changes;

### References
- [CoinMarketCap API](https://coinmarketcap.com/api/) or [CoinGecko API](https://www.coingecko.com/en/api) for tokens, including LikeCoin; 
- [Exchange Rates API](https://exchangeratesapi.io/) for flat currency;
- [Design](https://www.figma.com/file/oGew0i2s0N8IBm9tCpoLLI/%E8%BF%AD%E4%BB%A3%E8%A8%AD%E8%A8%88%E4%B8%AD%E7%B9%BC%E7%AB%99?node-id=4632%3A24917)

**Comment by gary02** [comment]
solution doc https://www.notion.so/matterslab/Currency-convertor-d417cab3a6bc451494b1000bd2a1bb3f 
api schema doc https://www.notion.so/matterslab/Currency-preference-setting-convert-ba2d4f2868ba437d92e9ec2db6440c0e

**Comment by devformatters** [comment]
@gary02 I believe it's done. Feel free to reopen.
