### ISSUE TITLE
关于matters.news登陆后页面无法显示的问题

### ISSUE THREAD

**Issue by globien** [thematters/developer-resource#177]
**Describe the bug**
我不知道这里是不是报告matters.news网站Bug的地方，我从该网站点击“开放社区”来到这里。问题描述如下：
1. 如果我不登陆，则网站一切正常。
2. 如果我点击某些按钮按要求登陆，选择连接加密钱包，则虽然登陆过程似乎没有任何问题，但登陆完成后（加密钱包已点击“签名”），matters网站则完全不显示任何内容，或仅显示一个很大的网站图标。
3. 我使用的是Brave浏览器，Mac OS。已经尝试过清理Cookie和重启Brave浏览器并重新登陆的方法，不能解决问题。

**To Reproduce**
1. Go to 'matters.news'
2. Click on '进入' or '创作'
4. 按要求登录，选择连接加密钱包
5. 完成登录后，页面为空白或仅有一个很大的matters图标

**Expected behavior**
应该回到matters正常的页面

**Screenshots**
<img width="916" alt="Screen Shot 2022-11-21 at 4 34 43 PM" src="https://user-images.githubusercontent.com/56852450/203162667-d0610db5-20f2-44b6-82c1-00f0571aa2ec.png">

**Desktop (please complete the following information):**
 - OS: Macos 
 - Browser Brave 
 - Version [Version 1.45.127 Chromium: 107.0.5304.110 (Official Build) (x86_64)](https://brave.com/latest/)

**Comment by denkeni** [comment]
只清除 cookies 可能不夠，建議清除網站資料（參考[官方文件](https://support.brave.com/hc/en-us/articles/360048833872)）。

若還有問題，可以寄信給官方支援信箱 hi@matters.news

**Comment by globien** [comment]
> 

谢谢，不好意思打搅了。（问题没解决，我是清除matters网站全部数据的。我再看看吧，不行的话单独发邮件。）
