### ISSUE TITLE
Feature request: user can tweak or add tags for their articles

### ISSUE THREAD

**Issue by askender** [thematters/developer-resource#2]
RT, 
I think it it useful for users.

**Comment by guoliu** [comment]
I think it is possible with mutation `putArticlesTags`, we just haven't developed the UI yet.

**Comment by guoliu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(5) article detail page edit mode](https://trello.com/c/3mjm7zhS/1508-5-article-detail-page-edit-mode)

**Comment by guoliu** [comment]
Implemented and deployed with https://github.com/thematters/matters-web/pull/1274 and https://github.com/thematters/matters-server/pull/1287
