### ISSUE TITLE
Audit Logs Service: Research & Design

### ISSUE THREAD

**Issue by devformatters** [thematters/developer-resource#243]
### Checklists

- [x] Design audit logs and change history
- [x] Output documentation

### References
- [doc](https://www.notion.so/matterslab/147392419ea24b74ac939ebbcf6a3f0e?pvs=4#7d4acbedebe344809b5a6f20e09f875f)

**Comment by robertu7** [comment]
https://www.notion.so/matterslab/Audit-Logs-9cdbede5196b4043962954cab108e893?pvs=4
