### ISSUE TITLE
Documentation on creating testing account and test stripe add value 

### ISSUE THREAD

**Issue by guoliu** [thematters/developer-resource#25]
**Is your feature request related to a problem? Please describe.**
There's currently no clear instruction on how to create test accounts in test environment and how to test adding value with stripe.

**Describe the solution you'd like**
We should add documentation on test environment and stripe test account to our wiki page. Test account can be activated by opening new articles in test environment, and stripe flow can be tested using with official stripe test accounts.

**Comment by guoliu** [comment]
Related: documentation on flow and order of merging branches.

**Comment by Carolusian** [comment]
Updated on Engineering Wiki > matters.news > Payment Related API

**Comment by devformatters** [comment]
Nice work 🫡
