### ISSUE TITLE
Scale up/down RDS w/o downitme

### ISSUE THREAD

**Issue by robertu7** [thematters/developer-resource#251]
[Discussion](https://matterslab.slack.com/archives/CH8BLCMTN/p1692634012886639?thread_ts=1692251383.075539&cid=CH8BLCMTN)

**Comment by gary02** [comment]
https://www.notion.so/matterslab/Modifying-Amazon-RDS-instance-class-with-minimal-downtime-6d076ef0cecc4041b64e233955258894
