### ISSUE TITLE
Adjust GIF support

### ISSUE THREAD

**Issue by devformatters** [thematters/developer-resource#253]
### Checklist
(This task involves both FE & BE)
- [x] Remove support of GIF from non-embed/avatar image upload;
- [x] Enable `anim=false` for non-embed/avatar images;
- [x] Size limitation 1MB for GIF avatar
- [ ] Make sure embed GIFs in article won't be set as cover (filter out at [Editor/SetCover](https://github.com/thematters/matters-web/tree/develop/src/components/Editor/SetCover))

### Refs
* [Discussion](https://matterslab.slack.com/archives/GA0R09FHN/p1695964349708939)
* [Discussion](https://matterslab.slack.com/archives/G8877EQMS/p1692956574504259?thread_ts=1692091034.466049&cid=G8877EQMS)
* [Discussion](https://matterslab.slack.com/archives/C88CK7Q7L/p1697157098767979)
* Related code: [here](https://github.com/thematters/matters-web/blob/develop/src/components/Cover/index.tsx#L22), [here](https://github.com/thematters/matters-web/blob/develop/src/common/utils/url.ts#L79-L81) and [here](https://github.com/thematters/matters-web/tree/develop/src/components/Editor/SetCover)
* https://developers.cloudflare.com/images/image-resizing/url-format/#anim

**Comment by tx0c** [comment]
or can call cloudflare to disable animation when set as any cover, show its 1st frame only

https://developers.cloudflare.com/images/image-resizing/url-format/#anim
