### ISSUE TITLE
Story: article insights

### ISSUE THREAD

**Issue by robertu7** [thematters/developer-resource#264]
### Description
As an author, I want to know the basic insights about articles I have published:
* **Number of readers: unique logged-in users + unique anonymous users by IP** (TBC: UV/PV from GA/analytics to product DB);
* Number of likes;
* Number of comments;
* Number of donations;

### References
* [design](https://www.figma.com/file/XLTES6FFpEuAVa3z0xj8mA/%E6%88%91%E7%9A%84%E5%89%B5%E4%BD%9C?type=design&node-id=250-13580&mode=design&t=EN1BaJ9WWswn92aN-0)

---

### Epic
* https://github.com/thematters/developer-resource/issues/258

### Implementations
- https://github.com/thematters/developer-resource/issues/275
- https://github.com/thematters/matters-server/issues/3623

**Comment by tx0c** [comment]
> unique anonymous users by IP (TBC: UV/PV from GA/analytics to product DB);
anonymous users by number of devices,  (e.g. multiple devices from a same coffee bar would share a single IP behind NAT )   just map the GA4 number of pseudo IDs
