### ISSUE TITLE
Design APIs and draft docs

### ISSUE THREAD

**Issue by devformatters** [thematters/developer-resource#275]
### Tasks
- [ ] Design APIs & reader data pipeline
- [ ] Output a tech doc about this

### Stories
- https://github.com/thematters/developer-resource/issues/264
- https://github.com/thematters/developer-resource/issues/262

**Comment by gary02** [comment]
https://www.notion.so/matterslab/Readers-GA-data-pipeline-and-My-Works-APIs-718f813f4ef44db1879b87e057cb269f
