### ISSUE TITLE
Post-processing of oversized images

### ISSUE THREAD

**Issue by robertu7** [thematters/developer-resource#296]
- [ ] post-process oversized images ([Cloudflare limitations](https://developers.cloudflare.com/images/cloudflare-images/upload-images/formats-limitations/))
- [ ] re-upload to Cloudflare Images with same path/assetId

**Comment by tx0c** [comment]
all direct supported images migration are done; results ~2000 images need client-side pre-process'ing of another round migration.

1. image size too big;     => shrink down
1. image dimension too big;     => shrink down
2. gif (too many frames, dimensions `height * width * frames` >100M)

**Comment by tx0c** [comment]
e.g.  resized from `1080 x 12671`  to `853x10000`, from 980K to 384KB;

```console
➸ curl -I 'https://assets.matters.news/embed/73551c7f-be1c-4a0f-9f94-af6352aa8413.png'
HTTP/2 200 
content-type: image/png
content-length: 980104
➸ curl -I 'https://imagedelivery.net/kDRCweMmqLnTPNlbum-pYA/prod/embed/73551c7f-be1c-4a0f-9f94-af6352aa8413.png/w=1376,h=5504,fit=scale-down'
HTTP/2 200 
date: Wed, 25 Oct 2023 00:44:46 GMT
content-type: image/jpeg
content-length: 384327
```
