### ISSUE TITLE
Prepare Instagram app for social sharing

### ISSUE THREAD

**Issue by devformatters** [thematters/developer-resource#297]
### Checklst
- [ ] Submit Meta/Instagram App Review
- [ ] Confirm available APIs and limitations (e.g. publish post)

### Refs
* [Discussion](https://matterslab.slack.com/archives/C05067EBWCE/p1697186370069839)
* https://developers.facebook.com/docs/instagram

**Comment by gary02** [comment]
It seem that Instagram do not provide way for web app social sharing
