### ISSUE TITLE
Story: renovated article main page

### ISSUE THREAD

**Issue by robertu7** [thematters/developer-resource#317]
### Description
To make a better reading experience, there are many parts to cover:
* Improved typography for content and new fonts for title & summary;
* Improved widgets like support and toolbar;
* Clear article states: archived and paywalled;
* ... and revised header & tags

### Epic
* https://github.com/thematters/developer-resource/issues/272

### Implementation
- https://github.com/thematters/developer-resource/issues/328
- https://github.com/thematters/developer-resource/issues/329
- https://github.com/thematters/developer-resource/issues/330
- https://github.com/thematters/developer-resource/issues/331
- https://github.com/thematters/developer-resource/issues/332
- https://github.com/thematters/developer-resource/issues/333

### References
* [Design](https://www.figma.com/file/gs3w7fKdHqk9u1nnDxPYlZ/%E4%BD%9C%E5%93%81%E9%A0%81?type=design&node-id=101-282&mode=dev)

**Comment by pitb2022** [comment]
- https://github.com/thematters/developer-resource/issues/328
- https://github.com/thematters/developer-resource/issues/329
- https://github.com/thematters/developer-resource/issues/330
- https://github.com/thematters/developer-resource/issues/331
- https://github.com/thematters/developer-resource/issues/332
- https://github.com/thematters/developer-resource/issues/333
- https://github.com/thematters/developer-resource/issues/334
