### ISSUE TITLE
Story: author sidebar

### ISSUE THREAD

**Issue by robertu7** [thematters/developer-resource#318]
### Description
To discover related articles and provide better context of collection, we have to revise the current article sidebar including:
* showing author collections;
* showing author's latest *N* articles; 
* showing recommended articles;

### Epic
* https://github.com/thematters/developer-resource/issues/272

### Implementations
* https://github.com/thematters/developer-resource/issues/334
* https://github.com/thematters/matters-server/issues/3697

### References
* [Design](https://www.figma.com/file/gs3w7fKdHqk9u1nnDxPYlZ/%E4%BD%9C%E5%93%81%E9%A0%81?type=design&node-id=261-32076&mode=dev)

**Comment by pitb2022** [comment]
- https://github.com/thematters/developer-resource/issues/334
