### ISSUE TITLE
Story: comment drawer

### ISSUE THREAD

**Issue by robertu7** [thematters/developer-resource#319]
### Description
Enhanced article comment area with new UI/UX.

### Epic
* https://github.com/thematters/developer-resource/issues/272

### Implementation
- https://github.com/thematters/developer-resource/issues/335
- https://github.com/thematters/developer-resource/issues/336
- https://github.com/thematters/developer-resource/issues/337
- https://github.com/thematters/developer-resource/issues/338
- https://github.com/thematters/matters-server/issues/3165

### References
* [Design](https://www.figma.com/file/gs3w7fKdHqk9u1nnDxPYlZ/%E4%BD%9C%E5%93%81%E9%A0%81?type=design&node-id=839-46340&mode=dev)
* Related ticket: https://github.com/thematters/matters-server/issues/3165

**Comment by pitb2022** [comment]
- https://github.com/thematters/developer-resource/issues/335
- https://github.com/thematters/developer-resource/issues/336
- https://github.com/thematters/developer-resource/issues/337
- https://github.com/thematters/developer-resource/issues/338
