### ISSUE TITLE
Implementation of Digital Nomad program

### ISSUE THREAD

**Issue by robertu7** [thematters/developer-resource#326]
#### Server
- [x] Cronjob for badge
- [x] vote counting implementation
- [x] email and in-app notification
- [x] doc for cron job mechanism

#### Client
- [x] Revise badge UI in user profile page
- [x] Sharing & Response through sharing url

#### Reference
- [rules](https://matters.town/@hi176/464035-nomad-matters-%E9%81%8A%E7%89%A7%E8%80%85%E8%A8%88%E7%95%AB%E5%95%9F%E5%8B%95-%E5%AF%A6%E8%B8%90%E4%B8%80%E7%A8%AE%E8%B2%A0%E8%B2%AC%E4%BB%BB%E7%9A%84%E6%95%B8%E5%AD%97%E9%81%8A%E6%B0%91%E7%94%9F%E6%B4%BB-bafybeigte4uj3y6myqxqrr6tbdkaitf4bvwayqkdsjb3oz3bwkg74asjj4)
- [design](https://www.figma.com/file/xXI3jxooZfrGbvD138gpAN/%E5%BE%BD%E7%AB%A0%E5%BE%AE%E8%AA%BF?type=design&node-id=108-363&mode=design)
- [thread](https://matterslab.slack.com/archives/C065L22E1MX/p1701167848222519)

**Comment by zeckli** [comment]
@tx0c I've added frontend design.

**Comment by tx0c** [comment]
- badge UI and emails mostly done, waiting translation copies

- lambda cronjob and on demand trigger run by admin

**Comment by tx0c** [comment]
[doc for cron job mechanism](https://www.notion.so/matterslab/Nomad-Badges-Campaign-0ec10ebe557948a9ae90e4ff33036f80)
