### ISSUE TITLE
New UX for the wallet page

### ISSUE THREAD

**Issue by proformatters** [thematters/developer-resource#33]
1- add LikeCoin setting button to the wallet page
2- wallet page UI upgrade 
3- remove LikeCoin wallet settings from the Settings Page

![image](https://user-images.githubusercontent.com/47885618/95046978-d1c62c80-0717-11eb-8b4a-d2ddcb788725.png)

**Comment by devformatters** [comment]
Have a new design for it. Close it and create proper and smaller tasks for this.
