### ISSUE TITLE
Support Area

### ISSUE THREAD

**Issue by pitb2022** [thematters/developer-resource#333]
- [ ] Reader Viewer
- [ ] Author Viewer
   - [ ] Edit Copy Dialog
   - [ ] Update Default Copy
   - [ ] Supporters Dialog
- [ ] Supporter’s Avatar Area
- [ ] Mobile Avatar is a small

**Comment by zeckli** [comment]
Also check this issue: https://feedback.matters.town/bug-reports/p/992893
