### ISSUE TITLE
Donation Drawer -- Line Pay

### ISSUE THREAD

**Issue by pitb2022** [thematters/developer-resource#339]
### Todos
 - [ ] Tabs
 - [ ] Line Pay 
	 - [ ] Select amount step
	 - [ ] Scan QRCode Step
	 - [ ] Processing Step
	 - [ ] Successful step
	 - [ ] Failure step
	 - [ ] Mobile Adaption

### Stories
- https://github.com/thematters/developer-resource/issues/358

**Comment by zeckli** [comment]
Close it since we will estimate the entire solution again.
