### ISSUE TITLE
Donation Drawer -- USDT

### ISSUE THREAD

**Issue by pitb2022** [thematters/developer-resource#341]
### Todos
- [ ] Desktop
- [ ] Mobile
- [ ] ~Allow logged-in user donate with any wallet address on USDT donation~

### Refs
* [Design](https://www.figma.com/file/gs3w7fKdHqk9u1nnDxPYlZ/%E4%BD%9C%E5%93%81%E9%A0%81?node-id=840%3A26814&mode=dev)
* [Discussion](https://matterslab.slack.com/archives/G8877EQMS/p1702541136424919?thread_ts=1702295898.469909&cid=G8877EQMS)
* https://github.com/thematters/developer-resource/issues/327
* https://github.com/thematters/matters-server/issues/3723

---

### Story
- https://github.com/thematters/developer-resource/issues/320

**Comment by zeckli** [comment]
This ticket has been replaced by others.
