### ISSUE TITLE
Donation Drawer -- LikeCoin

### ISSUE THREAD

**Issue by pitb2022** [thematters/developer-resource#342]
### Todos
- [ ] Desktop
- [ ] Mobile

### References
- [design](https://www.figma.com/file/gs3w7fKdHqk9u1nnDxPYlZ/%E4%BD%9C%E5%93%81%E9%A0%81?node-id=840%3A26766&mode=dev)

---

### Story
- https://github.com/thematters/developer-resource/issues/320

**Comment by zeckli** [comment]
This ticket has been replaced by others.
