### ISSUE TITLE
Donation Drawer -- Donation animation

### ISSUE THREAD

**Issue by pitb2022** [thematters/developer-resource#343]
### References
- [design](https://www.figma.com/file/gs3w7fKdHqk9u1nnDxPYlZ/%E4%BD%9C%E5%93%81%E9%A0%81?node-id=1348%3A53741&mode=dev)

---

### Story
- https://github.com/thematters/developer-resource/issues/320

**Comment by zeckli** [comment]
This ticket has been replaced by others.
