### ISSUE TITLE
Revise node APIs to support querying by hash

### ISSUE THREAD

**Issue by robertu7** [thematters/developer-resource#346]
### Blocker
* https://github.com/thematters/developer-resource/issues/348
* https://github.com/thematters/developer-resource/issues/365

### Checklist
* Confirm the new URL design with product team;
* (Server) APIs (`node`, `nodes`) to query via hash/id, DB changes;
* ~(Client) Change URL pattern of article detail page, tag detail page, etc.;~ (moved to https://github.com/thematters/matters-web/issues/4196)
* ~(Edge) Backward & forward compatibility (e.g. redirection using Cloudflare or Cloudflare Workers);~ (moved to https://github.com/thematters/developer-resource/issues/373)

---

### Story
- https://github.com/thematters/developer-resource/issues/372

**Comment by zeckli** [comment]
This [issue](https://github.com/thematters/matters-email/issues/227) reported by community is related.

**Comment by tx0c** [comment]
https://www.notion.so/matterslab/URL-Hash-Algorithms-c2400728b68d4747a7660dd5374944f8
