### ISSUE TITLE
Preparation for URL pattern changes

### ISSUE THREAD

**Issue by robertu7** [thematters/developer-resource#348]
### Description
As the [upcoming changes of URL patterns](https://github.com/thematters/developer-resource/issues/346) for pages like article details, we have to prepare a detailed plan for SEO migration and backward compatibility.

### Checklist
* SEO migration guide;
* Design for backward compatibility [0];

[0] Legacy URLs still can be accessed and redirect to new URLs (Cloudflare Workers or matters-web middleware?)

**Comment by tx0c** [comment]
https://www.notion.so/matterslab/SEO-migration-a4a76247023e4a7ab713708fbd5eae31
