### ISSUE TITLE
Costs estimation of cloudflare bulk redirects

### ISSUE THREAD

**Issue by robertu7** [thematters/developer-resource#375]
### Background

Based on https://github.com/thematters/developer-resource/issues/365, all traffic (URLs) will be routed to Clouldflare Workers since Bulk redirect cannot set a regex to match all legacy article URLs.

### Checklist
- [x] Estimate costs
- [ ] Find workaround to reduce costs (if any)

**Comment by tx0c** [comment]
https://www.notion.so/matterslab/Cloudflare-bulk-redirects-da9cac4343494af187c803f44325222f
