### ISSUE TITLE
Redis capacity planning

### ISSUE THREAD

**Issue by tx0c** [thematters/developer-resource#377]
### References
- [Discussion](https://matterslab.slack.com/archives/GA0R09FHN/p1708502859950399)

---
### Story
- https://github.com/thematters/developer-resource/issues/420

**Comment by tx0c** [comment]
Freeable Memory drops to a low point every a few months:

- ![Image](https://github.com/thematters/developer-resource/assets/49659410/b691c892-05a5-4ff2-82b0-104057cd110b)

**Comment by robertu7** [comment]
pause this ticket cuz there are still [many issues on cluster mode](https://matterslab.slack.com/archives/C88CK7Q7L/p1717295765927319?thread_ts=1717235972.491439&cid=C88CK7Q7L)
