### ISSUE TITLE
Frontend memory issue

### ISSUE THREAD

**Issue by zeckli** [thematters/developer-resource#412]
### Checklist
- [ ] Investigate root cause and fix it
- [ ] Enlist all relevant things into [monitoring plan](https://github.com/thematters/developer-resource/issues/401)

### Refs
- [Discussion](https://matterslab.slack.com/archives/C0613HR8WEL/p1712640611028969)
- [Discussion]( https://matterslab.slack.com/archives/C0613HR8WEL/p1712758889463459)
- [Report](https://matterslab.slack.com/archives/GFAQ01YMD/p1712640666345629) (might related)

### Story
* https://github.com/thematters/developer-resource/issues/418

**Comment by tx0c** [comment]
problems found:

- [ ] https://auth.matters.news/ still serving, mostly response with 500 internal errors
- [ ]

**Comment by tx0c** [comment]
mitigation in thematters/matters-web#4291
