### ISSUE TITLE
Sign up failed with red alert shows verification code input error. PM cannot reproduce in the test environment.

### ISSUE THREAD

**Issue by proformatters** [thematters/developer-resource#43]
![image](https://user-images.githubusercontent.com/47885618/97857534-db53ac00-1d38-11eb-863a-6493885a0bdf.png)

**Comment by devformatters** [comment]
Converted to [issue](https://github.com/thematters/matters-web/issues/1609).

**Comment by devformatters** [comment]
Close it.
