### ISSUE TITLE
Install memory monitoring script to client-side server on CI/CD deployment

### ISSUE THREAD

**Issue by robertu7** [thematters/developer-resource#433]
### Refs
* https://github.com/thematters/developer-resource/issues/412
* https://gist.github.com/tx0c/90c8353834f5bd4f7923c52bf7f24ac8
* [Discussion](https://matterslab.slack.com/archives/C88CK7Q7L/p1715734047627209?thread_ts=1715131902.544109&cid=C88CK7Q7L)

**Comment by tx0c** [comment]
resolved in : thematters/matters-web#4411 thematters/matters-web#4418

**Comment by tx0c** [comment]
resolved in : thematters/matters-web#4411 thematters/matters-web#4418
