### ISSUE TITLE
Stop metabase EC2 instance

### ISSUE THREAD

**Issue by robertu7** [thematters/developer-resource#440]
### Checklist
- [x] Remove `author_tags` table and related unused API;
- [ ] Stop ipfs-reachablity-monitoring;
- [x] Move the sitemap serving to S3/R2;

**Comment by gary02** [comment]
metabase ec2 is also serving IPNS-reachablity-monitoring, see https://github.com/thematters/uptime/issues/269

**Comment by robertu7** [comment]
https://github.com/thematters/matters-server/issues/3855
https://github.com/thematters/matters-server/pull/3860
https://github.com/thematters/matters-metabase/tree/main/sql
https://github.com/thematters/matters-server/tree/develop/db/sql
https://github.com/thematters/matters-server/pull/2629
https://github.com/thematters/matters-server/pull/2724
https://github.com/thematters/matters-server/pull/2880
