### ISSUE TITLE
Upgrade QF stats observable baord

### ISSUE THREAD

**Issue by zeckli** [thematters/developer-resource#457]
### Description
- (WIP)

### References
- [product doc](https://www.notion.so/matterslab/MVP-757455f40a444e2db6f43a2efee3aca3)

---

### Story
- https://github.com/thematters/developer-resource/issues/455

**Comment by robertu7** [comment]
[Refactor QF statistics notebook
](https://github.com/thematters/developer-resource/issues/466)
