### ISSUE TITLE
Upgrade toolbar and add the donation button in the toolbar

### ISSUE THREAD

**Issue by proformatters** [thematters/developer-resource#46]
<img width="818" alt="螢幕截圖 2020-11-10 下午7 37 53" src="https://user-images.githubusercontent.com/47885618/98669355-3d8d5c00-238c-11eb-87ad-5657258397da.png">
<img width="724" alt="螢幕截圖 2020-11-10 下午7 38 09" src="https://user-images.githubusercontent.com/47885618/98669388-454d0080-238c-11eb-93b9-a2a986176a98.png">

**Comment by devformatters** [comment]
Close it cuz move it to right repo.
