### ISSUE TITLE
Review and design APIs for free write

### ISSUE THREAD

**Issue by zeckli** [thematters/developer-resource#464]
### Description
- Design doc
- Break design into tasks

### References
- [design](https://www.figma.com/design/vDS1dPrYuM7EHTeIaA9cPs/%E8%87%AA%E7%94%B1%E5%AF%AB?node-id=908-35401&t=DQl8IDxlKNbmRcOv-1)

---

### Story
- https://github.com/thematters/developer-resource/issues/461

**Comment by gary02** [comment]
- design APIs and DB schema to support following use cases:
  -  free write events CRUD for OSS
  -  list current active events
  -  allow users  to join events
  -  list joined users of events
  -  list joined events of users
  -  publish articles to events
   - article detail show related event
  -  list articles of events with DAY filter
  -  list new badges
  -  notifications
  - block users

**Comment by gary02** [comment]
https://www.notion.so/matterslab/Free-Write-Campaign-1342b6a6c20142b1a89b3d8eccf8b8f6

**Comment by zeckli** [comment]
We're in implementing stage, so close this ticket.
