### ISSUE TITLE
Badges for 100+ donations and special contributions (operation team)

### ISSUE THREAD

**Issue by proformatters** [thematters/developer-resource#56]
<img width="872" alt="螢幕截圖 2020-12-09 上午11 43 55" src="https://user-images.githubusercontent.com/47885618/101574975-d2c75300-3a13-11eb-8bae-57976e4b7ca7.png">

- Badge 1 +tooltip 1 金馬達徽章；「支持超過100次」
- Badge 2+tooltip 2 扳手徽章；「馬特市建築師」
- Orange ring

**Comment by devformatters** [comment]
### API (5pt)
- Revise schema `info.badges`
- Add table for architect
- Toggle API for adding and removing architect
- 5 pt

### WEB UI (3pt)
- Badges with tooltip
- 3 pt

### OSS UI (5pt)
- Add UI for management

**Comment by devformatters** [comment]
This issue has been break down into:
- https://github.com/thematters/matters-server/issues/1860
- https://github.com/thematters/matters-oss/issues/525
- https://github.com/thematters/matters-web/issues/1918
